name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Substitua pela branch que você deseja usar
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Versão de Ruby compatível com Jekyll

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: |
          echo "exclude: ['node_modules', 'Gemfile', 'Gemfile.lock']" >> _config.yml
          bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site